apiVersion: v1
kind: Service
metadata:
  labels:
    app: telegraf
  name: telegraf
  namespace: iotmetrics
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    app: telegraf
