apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-path-influxdb-data
  namespace: iotmetrics
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-path-influxdb-config
  namespace: iotmetrics
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi
